### ISSUE TITLE
version 0.0.9 installation

### ISSUE THREAD

**Issue by kazuyakusastro** [malikolivier/aflak#7]
## pip (error)
kazuya@dospara2015:/data/kazuya/vis-ifu/aflak$ pip install aflak
Collecting aflak
  Using cached aflak-0.0.3.tar.gz
Requirement already satisfied: astropy in /home/kazuya/.local/lib/python2.7/site-packages (from aflak)
Collecting pyqtgraph (from aflak)
  Using cached pyqtgraph-0.10.0.tar.gz
Collecting PyQt5 (from aflak)
  Could not find a version that satisfies the requirement PyQt5 (from aflak) (from versions: )
No matching distribution found for PyQt5 (from aflak)

## dpkg (success!)
root@dospara2015:/data/kazuya/vis-ifu/aflak# dpkg -i aflak-0.0.9-debian-stretch.deb 
以前に未選択のパッケージ aflak を選択しています。
(データベースを読み込んでいます ... 現在 165546 個のファイルとディレクトリがインストールされています。)
aflak-0.0.9-debian-stretch.deb を展開する準備をしています ...
aflak (0.0.9-1) を展開しています...
aflak (0.0.9-1) を設定しています ...
gnome-menus (3.13.3-9) のトリガを処理しています ...
desktop-file-utils (0.23-1) のトリガを処理しています ...
mime-support (3.60) のトリガを処理しています ...
root@dospara2015:/data/kazuya/vis-ifu/aflak# exit
ログアウト
kazuya@dospara2015:/data/kazuya/vis-ifu/aflak$ aflak
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
WARNING: FITSFixedWarning: PLATEID = 7443 / Current plate 
a string value was expected. [astropy.wcs.wcs]
Opened file: /data/kazuya/vis-ifu/manga-7443-12703-LINCUBE.fits
Filename: /data/kazuya/vis-ifu/manga-7443-12703-LINCUBE.fits
...

**Comment by malikolivier** [comment]
Thanks!

Regarding installation in pip, it fails because python2 is not supported. On `Debian Stretch`, `pip` defaults to python2. You must use do as below:

```bash
pip3 install aflak
````

And then you should be able to run the package using python3 as below:

```bash
python3 -m aflak
````

I will make the requirements clearer in the README.
